
if (!Srims.papers) 
    Ext.namespace('Srims.papers');

Srims.papers.PaperGridPanel_ColumnModel = function(){
    Srims.papers.PaperGridPanel_ColumnModel.superclass.constructor.call(this, [{
        header: "id",
        dataIndex: 'id',
        hidden: true,
        hideable: false
    }, {
        header: "论文名称",
        dataIndex: 'name',
        sortable: true,
        hidden: false,
        renderer: function(value){
            return String.format('<span title="{0}">{0}</span>', value);
        }
    }, {
        header: "magazineID",
        dataIndex: "magazineID",
        hidden: true,
        hideable: false
    }, {
        header: "发表杂志",
        dataIndex: 'fullName',
        sortable: true,
        hidden: false,
        renderer: function(value){
            return String.format('<span title="{0}">{0}</span>', value);
        }
    }, {
        header: "发表年份",
        dataIndex: 'publishYear',
        width: 60,
        sortable: true,
        hidden: false
    }, {
        header: "影响因子",
        dataIndex: 'influenceFactorOfPaper',
        width: 60,
        sortable: true,
        renderer: InfluenceFactor.render,
        hidden: false
    }, {
        header: "收录",
        dataIndex: 'indexed',
        width: 60,
        sortable: false,
        hidden: false
    }, {
        header: "所属学院",
        dataIndex: 'collegeName',
        width: 60,
        sortable: true,
        hidden: false
    }, {
        header: "通讯作者",
        dataIndex: 'linkManName',
        width: 60,
        sortable: true,
        hidden: false
    }, {
        header: "第一作者",
        dataIndex: 'firstAuthorName',
        width: 60,
        sortable: true,
        hidden: false
    }, {
        header: "类型",
        dataIndex: 'type',
        width: 60,
        sortable: true,
        hidden: true,
        renderer: Srims.papers.PaperTypeRender
    }, {
        header: "引用频次",
        dataIndex: 'citeFrequencyOfPaper',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "发表日期",
        dataIndex: 'publishDate',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "期次",
        dataIndex: 'documentNumber',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "卷号",
        dataIndex: 'volume',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "起始页码",
        dataIndex: 'startPage',
        width: 60,
        sortable: false,
        hidden: true
    }, {
        header: "结束页码",
        dataIndex: 'endPage',
        width: 60,
        sortable: false,
        hidden: true
    }, {
        header: "页数",
        dataIndex: 'pages',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "分区",
        dataIndex: 'subAirer',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "作者关键词",
        dataIndex: 'authorKeyWord',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "关键词",
        dataIndex: 'keyWord',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "通讯作者地址",
        dataIndex: 'linkManAddress',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "通讯作者Email",
        dataIndex: 'linkManEmail',
        width: 60,
        sortable: false,
        hidden: true
    }, {
        header: "通讯作者署名单位",
        dataIndex: 'linkManSignUnit',
        width: 60,
        sortable: true,
        hidden: true,
        renderer: Srims.papers.SignUnitRender
    }, {
        header: "第一作者署名单位",
        dataIndex: 'firstAuthorSignUnit',
        width: 60,
        sortable: true,
        hidden: true,
        renderer: Srims.papers.SignUnitRender
    }, {
        header: "我校署名位次",
        dataIndex: 'signOrder',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "所属实验室",
        dataIndex: 'lab',
        width: 60,
        sortable: true,
        hidden: true
    }, {
        header: "ISIUniqueArticleIdentifier",
        dataIndex: 'isiUniqueArticleIdentifier',
        width: 60,
        sortable: true,
        hidden: true
    }]);
    
    this.defaultSortable = false;
}
Ext.extend(Srims.papers.PaperGridPanel_ColumnModel, Ext.grid.ColumnModel);
