
if (!Srims.common)
    Ext.namespace('Srims.common');

Srims.common.OutsourcingShowPanel_AllocationInfo_ColumnModel = function(expander) {
    Srims.common.OutsourcingShowPanel_AllocationInfo_ColumnModel.superclass.constructor.call(this, [expander,{
        header: 'ID',
        dataIndex: 'projectID',
        hidden: true
    }, {
        header: "编号",
        dataIndex: 'number',
        width: 100,
        sortable: true,
        hidden: false
    }, {
        header: "名称",
        dataIndex: 'name',
        sortable: true,
        hidden: false,
        renderer: function(value) {
            return String.format('<span title="{0}">{0}</span>', value);
        }
    }, {
        header: "负责人",
        dataIndex: 'principal',
        width: 40,
        sortable: true,
        hidden: false
    }, {
        header: "所属学院",
        dataIndex: 'principalCollege',
        width: 40,
        sortable: false,
        hidden: true
    }, {
        header: "等级",
        dataIndex: 'rankName',
        width: 40,
        sortable: true,
        hidden: false
    }, {
        header: "类型",
        dataIndex: 'typeName',
        width: 80,
        sortable: true,
        hidden: false
    }, {
        header: "类型（简称）",
        dataIndex: 'typeShortName',
        width: 80,
        sortable: true,
        hidden: false
    }, {
        header: "到校经费",
        dataIndex: 'fundTotal',
        width: 60,
        sortable: true,
        hidden: false,
        renderer: Money.render
    }, {
        header: "已到经费",
        dataIndex: 'fundReceived',
        width: 60,
        sortable: true,
        hidden: false,
        renderer: Money.render
    }, {
        header: "开始日期",
        dataIndex: 'startDate',
        width: 80,
        sortable: true,
        hidden: false,
        renderer: Date.render
    }, {
        header: "结束日期",
        dataIndex: 'endDate',
        width: 80,
        sortable: true,
        hidden: false,
        renderer: Date.render
    }, {
        header: "负责人工作证号",
        dataIndex: 'principalNumber',
        sortable: false,
        hidden: true
    }, {
        header: "状态",
        dataIndex: 'state',
        width: 30,
        sortable: false,
        hidden: true,
        renderer: Srims.projects.projectStateRender
    }, {
        header: "级别",
        dataIndex: 'level',
        sortable: false,
        hidden: true,
        width: 10,
        renderer: Srims.projects.projectLevelRender
    }, {
        header: "所属学科",
        dataIndex: 'subjectName',
        sortable: false,
        hidden: true
    }, {
        header: "研究类型",
        dataIndex: 'researchType',
        sortable: false,
        hidden: true
    }, {
        header: "合作类型",
        dataIndex: 'cooperationType',
        sortable: false,
        hidden: true
    }, {
        header: "所属基地",
        dataIndex: 'baseName',
        sortable: false,
        hidden: true
    }, {
        header: "保密",
        dataIndex: 'isSecret',
        sortable: false,
        hidden: true,
        renderer: Boolean.render
    }, {
        header: "委托负责人",
        dataIndex: 'principalDelegate',
        sortable: false,
        hidden: true
    }, {
        header: "建立人",
        dataIndex: 'creator',
        sortable: false,
        hidden: true
    }, {
        header: "建立日期",
        dataIndex: 'createDate',
        sortable: true,
        hidden: true,
        renderer: Date.render
    }, {
        header: "公司所在地",
        dataIndex: 'corporationPlace',
        sortable: false,
        hidden: true
    }, {
        header: "资助类别",
        dataIndex: 'supportCategoryName',
        sortable: false,
        hidden: true
    }, {
        header: "资助领域",
        dataIndex: 'supportField',
        sortable: false,
        hidden: true
    }, {
        header: "资助子领域",
        dataIndex: 'supportField',
        sortable: false,
        hidden: true
    }, {
        header: '项目计划分配外协额度',
        dataIndex: 'projectOutAmount',
        hidden: false,
        renderer: Money.render
    }, {
        header: '项目已分外协',
        dataIndex: 'allocatedAmount',
        hidden: false,
        renderer: Money.render
}])
    }
    Ext.extend(Srims.common.OutsourcingShowPanel_AllocationInfo_ColumnModel, Ext.grid.ColumnModel);
