if (!Srims.fund)
    Ext.namespace('Srims.fund');
Srims.fund.FundAllocationGridPanel_ColumnModel = function(isShowProjectName) {
    Srims.fund.FundAllocationGridPanel_ColumnModel.superclass.constructor.call(this, [{
        header: 'id',
        hidden: true
    }, {
        header: '项目编号',
        dataIndex: 'projectNumber',
        width: 300,
        hidden: !isShowProjectName
    }, {
        header: '分配项目',
        dataIndex: 'projectName',
        width: 300,
        hidden: !isShowProjectName
    }, {
        header: '分配时间',
        dataIndex: 'allocationDateTime',
        sortable: true,
        width: 100,
        renderer: Date.render
    }, {
        header: '分配总额',
        dataIndex: 'allocationTotal',
        sortable: true,
        width: 80,
        renderer: Money.render
    }, {
        header: '直接费用',
        dataIndex: 'allocationIn',
        width: 80,
        renderer: Money.render
    }, {
        header: '项目总绩效',
        dataIndex: 'PerformanceTotal',
        width: 80,
        renderer: Money.render,
        hidden: !isShowProjectName
    }, {
        header: '校内绩效',
        dataIndex: 'overheadPerformancePay',
        width: 80,
        renderer: Money.render,
        hidden: !isShowProjectName
    }, {
        header: '课题组间接费用及绩效',
        dataIndex: 'overheadExpensesExpert',
        width: 80,
        renderer: Money.render
    }, {
        header: '外协分配',
        dataIndex: 'allocationOut',
        width: 80,
        renderer: Money.render
    }, {
        header: '当前状态',
        dataIndex: 'state',
        sortable: true,
        width: 60,
        renderer: Srims.fund.fundAllocationStateRender
    }, {
        header: '当前状态时间',
        dataIndex: 'dateTime',
        width: 100,
        renderer: Date.render
    }, {
        id: 'operator',
        header: '当前状态操作人',
        dataIndex: 'operator'
}])
    }
    Ext.extend(Srims.fund.FundAllocationGridPanel_ColumnModel, Ext.grid.ColumnModel);