
if (!Srims.projects) 
    Ext.namespace('Srims.projects');

Srims.projects.projectGridPanel_ColumnModel = function(){
    Srims.projects.projectGridPanel_ColumnModel.superclass.constructor.call(this, [{
        header: "id",
        hidden: true,
        hideable: false
    }, {
        header: "编号",
        dataIndex: 'number',
        width: 100,
        sortable: true,
        hidden: false
    }, {
        header: "名称",
        dataIndex: 'name',
        sortable: true,
        hidden: false,
        renderer: function(value){
            return String.format('<span title="{0}">{0}</span>', value);
        }
    }, {
        header: "负责人",
        dataIndex: 'principal',
        width: 40,
        sortable: true,
        hidden: false
    }, {
        header: "所属学院",
        dataIndex: 'principalCollege',
        width: 40,
        sortable: false,
        hidden: true
    }, {
        header: "等级",
        dataIndex: 'rankName',
        width: 40,
        sortable: true,
        hidden: false
    }, {
        header: "类型",
        dataIndex: 'typeName',
        width: 80,
        sortable: true,
        hidden: false
    }, {
        header: "类型（简称）",
        dataIndex: 'typeShortName',
        width: 80,
        sortable: true,
        hidden: false
    }, {
        header: "到校经费",
        dataIndex: 'fundTotal',
        width: 60,
        sortable: true,
        hidden: false,
        renderer: Money.render
    }, {
        header: "已到经费",
        dataIndex: 'fundReceived',
        width: 60,
        sortable: true,
        hidden: false,
        renderer: Money.render
    }, {
        header: "开始日期",
        dataIndex: 'startDate',
        width: 80,
        sortable: true,
        hidden: false,
        renderer: Date.render
    }, {
        header: "结束日期",
        dataIndex: 'endDate',
        width: 80,
        sortable: true,
        hidden: false,
        renderer: Date.render
    }, {
        header: "负责人工作证号",
        dataIndex: 'principalNumber',
        sortable: false,
        hidden: true
    }, {
        header: "状态",
        dataIndex: 'state',
        width: 30,
        sortable: false,
        hidden: true,
        renderer: Srims.projects.projectStateRender
    }, {
        header: "级别",
        dataIndex: 'level',
        sortable: false,
        hidden: true,
        width: 10,
        renderer: Srims.projects.projectLevelRender
    }, {
        header: "所属学科",
        dataIndex: 'subjectName',
        sortable: false,
        hidden: true
    }, {
        header: "研究类型",
        dataIndex: 'researchType',
        sortable: false,
        hidden: true
    }, {
        header: "合作类型",
        dataIndex: 'cooperationType',
        sortable: false,
        hidden: true
    }, {
        header: "所属基地",
        dataIndex: 'baseName',
        sortable: false,
        hidden: true
    }, {
        header: "保密",
        dataIndex: 'isSecret',
        sortable: false,
        hidden: true,
        renderer: Boolean.render
    }, {
        header: "委托负责人",
        dataIndex: 'principalDelegate',
        sortable: false,
        hidden: true
    }, {
        header: "建立人",
        dataIndex: 'creator',
        sortable: false,
        hidden: true
    }, {
        header: "建立日期",
        dataIndex: 'createDate',
        sortable: true,
        hidden: true,
        renderer: Date.render
    }, {
        header: "公司所在地",
        dataIndex: 'corporationPlace',
        sortable: false,
        hidden: true
    }, {
        header: "资助类别",
        dataIndex: 'supportCategoryName',
        sortable: false,
        hidden: true
    }, {
        header: "资助领域",
        dataIndex: 'supportField',
        sortable: false,
        hidden: true
    }, {
        header: "资助子领域",
        dataIndex: 'supportField',
        sortable: false,
        hidden: true
    }, {
        header: "硬件分配",
        dataIndex: 'fundAlreadyHardware',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "已分配经费",
        dataIndex: 'fundAlreadyTotal',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "已分配校内经费",
        dataIndex: 'fundAlreadyIn',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "已分配外协",
        dataIndex: 'fundAlreadyOut',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "合同额",
        dataIndex: 'fundContract',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "经费来源",
        dataIndex: 'fundFrom',
        sortable: false,
        hidden: true
    }, {
        header: "来款单位",
        dataIndex: 'fundFromUnit',
        sortable: false,
        hidden: true
    }, {
        header: "来款单位地址",
        dataIndex: 'fundFromUnitAddress',
        sortable: false,
        hidden: true
    }, {
        header: "计划外协",
        dataIndex: 'fundPlanOut',
        sortable: true,
        hidden: true,
        renderer: Money.render
          }, {
        header: "设备购置费",
        dataIndex: 'equipmentCost',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "计划硬件费",
        dataIndex: 'fundPlanHardware',
        sortable: true,
        hidden: true,
              renderer: Money.render  
    }, {
        header: "计划校内分配",
        dataIndex: 'fundPlanIn',
        sortable: false,
        hidden: true,
        renderer: Money.render
    }, {
        header: "总校内管理费",
        dataIndex: 'overheadExpenseInTotal',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "总外协管理费",
        dataIndex: 'overheadExpenseOutTotal',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "已收校内管理费",
        dataIndex: 'overheadExpensesAlreadyIn',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "已收外协管理费",
        dataIndex: 'overheadExpensesAlreadyOut',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "校内基准间接费",
        dataIndex: 'overheadExpensesInStandard',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "校内基准绩效",
        dataIndex: 'PerformanceInStandard',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "项目间接费用",
        dataIndex: 'indirectCosts',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "项目绩效",
        dataIndex: 'projectPerformancePay',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "校内绩效",
        dataIndex: 'performancePay',
        sortable: true,
        hidden: true,
        renderer: Money.render
    }, {
        header: "备注",
        dataIndex: 'remark',
        sortable: false,
        hidden: true
    }]);
    
    this.defaultSortable = false;
}
Ext.extend(Srims.projects.projectGridPanel_ColumnModel, Ext.grid.ColumnModel);
